### ISSUE TITLE
WordsByCharacter data

### ISSUE THREAD

**Issue by matthew-brett** [MokoSan/FSharpAdvent#1]
I'm very interested to use your `WordsByCharacter` data.  Could you say a bit more about where it comes from?  Sorry, I do not know F#, and a few quick greps didn't help me to see where in the code, you get this data.

Thanks a lot for any help.

**Comment by MokoSan** [comment]
Hi @matthew-brett , apologies for the late reply. As far as I remember, I found that dataset somewhere online i.e. I didn't parse it from some raw source but used it as is. Feel free to use any of the data / code from this repo. 

Have fun,
Moko

**Comment by matthew-brett** [comment]
Thanks a lot for the update.
